// ============================================================
// GALLERY MODULE — Masonry photo grid + lightbox
// Reads from data/photos.json (generated by scan_photos.py)
// ============================================================

const GalleryModule = (() => {

  let allPhotos = [];
  let filteredPhotos = [];
  let currentIndex = 0;
  const PAGE_SIZE = 40;
  let loadedCount = 0;
  let activeFilter = 'all';

  // ─── Initialize ─────────────────────────────────────────────
  async function init() {
    await loadPhotos();
    if (allPhotos.length > 0) {
      buildFilters();
      renderPage();
      initLightbox();
      document.getElementById('galleryEmpty').style.display = 'none';
    } else {
      document.getElementById('galleryEmpty').style.display = 'block';
    }
  }

  // ─── Load photos.json ─────────────────────────────────────────
  async function loadPhotos() {
    try {
      const res = await fetch('data/photos.json');
      if (!res.ok) throw new Error('photos.json not found');
      const data = await res.json();
      allPhotos = data.photos || [];
      filteredPhotos = [...allPhotos];
      console.log(`Gallery: loaded ${allPhotos.length} photos`);
    } catch (e) {
      console.log('Gallery: No photos.json found. Run scan_photos.py to import photos.');
      allPhotos = [];
      filteredPhotos = [];
    }
  }

  // ─── Build filter buttons ─────────────────────────────────────
  function buildFilters() {
    const container = document.getElementById('galleryFilters');
    // Clear existing except "all"
    container.innerHTML = '<button class="filter-btn active" data-filter="all">ALL PHOTOS</button>';

    // Get unique trip IDs
    const tripIds = [...new Set(allPhotos.map(p => p.trip_id))];
    tripIds.forEach(tripId => {
      const trip = ENDEMAN_LEGACY.trips.find(t => t.id === tripId);
      if (!trip) return;
      const btn = document.createElement('button');
      btn.className = 'filter-btn';
      btn.dataset.filter = tripId;
      btn.innerHTML = `${trip.emoji} ${trip.destination}`;
      container.appendChild(btn);
    });

    // Bind filters
    container.querySelectorAll('.filter-btn').forEach(btn => {
      btn.addEventListener('click', () => {
        container.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
        btn.classList.add('active');
        activeFilter = btn.dataset.filter;
        applyFilter();
      });
    });
  }

  function applyFilter() {
    if (activeFilter === 'all') {
      filteredPhotos = [...allPhotos];
    } else {
      filteredPhotos = allPhotos.filter(p => p.trip_id === activeFilter);
    }
    loadedCount = 0;
    document.getElementById('galleryGrid').innerHTML = '';
    renderPage();
  }

  // ─── Render a page of photos ──────────────────────────────────
  function renderPage() {
    const grid = document.getElementById('galleryGrid');
    const page = filteredPhotos.slice(loadedCount, loadedCount + PAGE_SIZE);
    const loadMoreBtn = document.getElementById('galleryLoadMore');

    page.forEach((photo, i) => {
      const item = buildGalleryItem(photo, loadedCount + i);
      grid.appendChild(item);
    });

    loadedCount += page.length;

    // Show/hide load more
    if (loadedCount < filteredPhotos.length) {
      loadMoreBtn.style.display = 'block';
    } else {
      loadMoreBtn.style.display = 'none';
    }
  }

  // ─── Build gallery item ───────────────────────────────────────
  function buildGalleryItem(photo, index) {
    const item = document.createElement('div');
    item.className = 'gallery-item';
    item.dataset.index = index;

    const trip = ENDEMAN_LEGACY.trips.find(t => t.id === photo.trip_id);
    const tripName = trip ? trip.destination : '';
    const locationName = photo.location_name || photo.trip_id || '';
    const dateStr = photo.date ? formatDate(photo.date) : '';
    const gpsStr = (photo.lat && photo.lng)
      ? `${photo.lat.toFixed(4)}°, ${photo.lng.toFixed(4)}°`
      : '';

    const thumbPath = photo.thumb || photo.path;

    item.innerHTML = `
      <img
        src="${thumbPath}"
        alt="${locationName}"
        loading="lazy"
        onerror="this.parentElement.style.display='none'"
      >
      <div class="gallery-item-overlay">
        <div class="gallery-item-info">
          <div class="gallery-item-location">
            <i class="fas fa-map-marker-alt"></i>
            ${locationName || tripName}
          </div>
          ${dateStr ? `<div class="gallery-item-date">${dateStr}</div>` : ''}
        </div>
      </div>
      ${gpsStr ? `<div class="gallery-item-gps">${gpsStr}</div>` : ''}
    `;

    item.addEventListener('click', () => openLightbox(index));
    return item;
  }

  // ─── Lightbox ─────────────────────────────────────────────────
  function initLightbox() {
    const lightbox = document.getElementById('lightbox');
    const backdrop = document.getElementById('lightboxBackdrop');
    const closeBtn = document.getElementById('lightboxClose');
    const prevBtn = document.getElementById('lightboxPrev');
    const nextBtn = document.getElementById('lightboxNext');
    const loadMoreBtn = document.getElementById('btnLoadMore');

    backdrop.addEventListener('click', closeLightbox);
    closeBtn.addEventListener('click', closeLightbox);
    prevBtn.addEventListener('click', () => navigateLightbox(-1));
    nextBtn.addEventListener('click', () => navigateLightbox(1));

    if (loadMoreBtn) {
      loadMoreBtn.addEventListener('click', renderPage);
    }

    document.addEventListener('keydown', e => {
      if (!lightbox.classList.contains('open')) return;
      if (e.key === 'ArrowLeft') navigateLightbox(-1);
      if (e.key === 'ArrowRight') navigateLightbox(1);
      if (e.key === 'Escape') closeLightbox();
    });
  }

  function openLightbox(index) {
    currentIndex = index;
    showPhoto(currentIndex);
    document.getElementById('lightbox').classList.add('open');
    document.body.style.overflow = 'hidden';
  }

  function closeLightbox() {
    document.getElementById('lightbox').classList.remove('open');
    document.body.style.overflow = '';
  }

  function navigateLightbox(dir) {
    currentIndex = (currentIndex + dir + filteredPhotos.length) % filteredPhotos.length;
    showPhoto(currentIndex);
  }

  function showPhoto(index) {
    const photo = filteredPhotos[index];
    if (!photo) return;

    const img = document.getElementById('lightboxImg');
    const loading = document.getElementById('lightboxLoading');

    loading.style.display = 'block';
    img.style.opacity = 0;

    img.onload = () => {
      loading.style.display = 'none';
      img.style.opacity = 1;
      img.style.transition = 'opacity 0.3s ease';
    };

    img.src = photo.path;

    const trip = ENDEMAN_LEGACY.trips.find(t => t.id === photo.trip_id);

    // Location
    const locText = photo.location_name || (trip ? trip.destination : '');
    document.getElementById('lightboxLocationText').textContent = locText;

    // Date
    document.getElementById('lightboxDate').textContent = photo.date ? formatDate(photo.date) : '';

    // Trip name
    document.getElementById('lightboxTrip').textContent = trip ? `${trip.emoji} ${trip.destination}` : '';

    // Counter
    document.getElementById('lightboxCounter').textContent = `${index + 1} / ${filteredPhotos.length}`;

    // GPS coords
    const coords = document.getElementById('lightboxCoords');
    if (photo.lat && photo.lng) {
      coords.textContent = `${photo.lat.toFixed(5)}°, ${photo.lng.toFixed(5)}°`;
      coords.style.display = 'block';
    } else {
      coords.style.display = 'none';
    }

    img.alt = locText;
  }

  // ─── Helpers ──────────────────────────────────────────────────
  function formatDate(dateStr) {
    if (!dateStr) return '';
    try {
      const d = new Date(dateStr + 'T12:00:00');
      return d.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    } catch {
      return dateStr;
    }
  }

  return { init };
})();
